### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by brianrobt** [pasce/daemon-skeleton-linux-c#2]
@pasce thanks for the awesome materials here!

At the end of the README in the "Further reading" section, the second link seems to be broken, and perhaps even the domain is inactive: http://www.enderunix.org/docs/eng/daemon.php

```sh
$ ping enderunix.org
PING enderunix.org (64.90.191.122) 56(84) bytes of data.
^C
--- enderunix.org ping statistics ---
9 packets transmitted, 0 received, 100% packet loss, time 8173ms
```

**Comment by pasce** [comment]
@thompsonbrian Thank you. I removed the dead link.
